# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOy8VsUfMd-ZpnkApTzIKxv-yXfvLNAD

ASSIGNMENT WEEK 3
"""

#import library that is required for handling data
import pandas as pd
import numpy as np

#Load the Titanic dataset
#Learn about the data using head()
df=pd.read_csv("/content/Titanic-Dataset.csv")
df.head()

#To understand how many columns and rows Available
df.shape

#To get summary of data
df.info()

#Find the number of null values
df.isnull().sum()

#summary statistics of data
df.describe()

#DATA CLEANING
#Filling the null values in the age using mean

df["Age"].fillna(df["Age"].mean(),inplace=True)

#Filling the null values in the embarked using mode
#mode() will give series list to get the highest frequency we use mode()[0]
df["Embarked"].fillna(df["Embarked"].mode()[0],inplace=True)

#Filling the null values in the cabin column using fillna
#in cabin column i Used unknown for the null values
df["Cabin"].fillna("Unknown",inplace=True)

df.isnull().sum()

df.head()

#Data Manipulation
df["FamilySize"]=df["SibSp"]+df["Parch"]+1
df.groupby('Sex')['Survived'].mean()
df.head()

#Data Visualization Library
import matplotlib.pyplot as plt
import seaborn as sns

#used countplot to visualize the count of survived
sns.countplot(x="Survived",data=df)

#Visualization of survival of people by age through boxplot
sns.boxplot(x="Survived",y="Age",data=df)

sns.heatmap(df.select_dtypes(include="number").corr(),annot=True)

sns.histplot(df['Age'])

#used this to understand the relationship between multiple numerical values
sns.pairplot(df,hue="Sex")

#Feature Engineering
#Creating a new column of people who are alone
df["IsAlone"]=(df["FamilySize"]==1).astype(int)

#Age Group category by age in a new column
df['AgeGroup']=pd.cut(df["Age"],bins=[0,12,18,35,50,60,80],labels=["child","Teen","Young","Adult","Senior","Old"])

#Divide the fair in 4 equal parts
df["FareGroup"]=pd.qcut(df["Fare"],4,labels=["Low","Medium","High","Expensive"])

df.head()

#Simple vizualization
#Survive - Yes=1,No=0
#by thiss visualization we see that most of the young people did not survive
sns.countplot(x="AgeGroup",hue="Survived",data=df)