# -*- coding: utf-8 -*-
"""Abinaya_DataScience_Week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQ1-xdmtFWqW2UOeRVAcvXIl3kLPvVq7

WEEK ASSIGNMENT 2

Name: Abinaya S

Course: Data Science
"""

#Task 1
#Create a function to print the results
def arithmetic_operations(a,b):
  print("Arithmetic operations of any two numbers")
  #f is used for formatting strings
  print(f"Addition: {a+b}")
  print(f"Subtraction: {a-b}")
  print(f"Multiplication: {a*b}")
  #check for 0 to ensure the division result iss not infinity
  if b!=0:
    print(f"Division {a/b}")
    print(f"Modulus {a%b}")
  else:
    print("ERROR:Division is not possible with Zero")
  print(f"Exponent: {a**b}")

#get input from user
n1=int(input("Enter first number:"))
n2=int(input("Enter Second Number:"))
#call the function to print results
print(arithmetic_operations(n1,n2))

#task 2
#import numpy library to convert list into library
import numpy as np
#create a list of 10 numbers
a=[1,2,3,4,5,6,7,8,9,10]
#to find length, maximum and minimum of the list
print(f"Length:{len(a)}")
print(f"Maximum:{max(a)}")
print(f"Minimum:{min(a)}")

#to add new element to the list
a.append(11)
print(f"Adding new element using append: {a}")
a.extend([12,13,14])
print(f"Adding new elements using extend: {a}")

#to remove the element from the list
a.pop()
print(f"Deleting the last element using pop: {a}")
a.remove(3)
print(f"Deleting the element using remove: {a}")

#to sort the element in ascending and descending order
print(f"Sorting in ascending order:{sorted(a)}")
print(f"Sorting in ascending order:{sorted(a,reverse=True)}")

#to convert the list into numpy array
arr=np.array(a)
#to find the mean , median and standard deviation
print(f"Mean:{np.mean(arr)}")
print(f"Median:{np.median(arr)}")
print(f"Standard Deviation:{np.std(arr)}")

#task 3
#Create a dictionary
student = [
    {"name": "Abinaya", "age": 20, "course": "Data Science", "marks": 96},
    {"name": "Karthik", "age": 21, "course": "Computer Science", "marks": 88},
    {"name": "Divya", "age": 19, "course": "Artificial Intelligence", "marks": 91},
    {"name": "Rahul", "age": 22, "course": "Machine Learning", "marks": 83}
]
#as i have given multiple values i formatted it as list and to fetch the dictionary i have to unbind the list
for students in student:
#Now we have dictionary to be displayed
  for key,value in student[0].items():
    print(f"{key}:{value}")
  print(" ")
for students in student:
#Grade is assigned for mark based using if elif else
  if students["marks"]>95:
    students["grade"]="O"
  elif students["marks"]>90:
    students["grade"]="D"
  elif students["marks"]>85:
    students["grade"]="A"
  elif students["marks"]>80:
    students["grade"]="B"
  else:
    students["grade"]="C"

  print(students)
#Created a set of unique course in the dictionary
courses=set()
for students in student:
  courses.add(students["course"])
print(courses)
#created a sample set of 2
set1={"python","AI","ML"}
set2={"AI","Data Science","ML"}
#performed set operations
print(set1.union(set2))
print(set1.intersection(set2))
print(set1.difference(set2))

#task 4
#Created a file named student.txt and written 6 students details of name, course and mark
with open("student.txt","w") as file:
    file.write("Abinaya,Data Science,96\n")
    file.write("Karthik,Computer Science,88\n")
    file.write("Divya,Artificial Intelligence,91\n")
    file.write("Rahul,Machine Learning,83\n")
    file.write("Rihana,Python,70\n")
    file.write("Siva,Computer Technology,90\n")
#read the file
with open("student.txt","r") as file:
#read one line at a time
  for line in file:
#strip() will remove the extra space and split() will split each data by comma
    name,course,marks=line.strip().split(",")
#since mark is in string convert it to integer
    marks=int(marks)
#display the mark above 75
    if marks>75:
      print(f"{name}-{course}-{marks}")